### ISSUE TITLE
Allow other factories syntaxes

### ISSUE THREAD

**Issue by wrpinheiro** [wrpinheiro/easy-factory#1]
Easy factory is prepared to deal only with "factory gilr" syntax in factories definition but it could also deal with JSON syntax:

``` javascript
{
  "factory": "simple_user",
  "class": "br.com.easyfactory.model.User"
  "attributes": {
    "id": 1234
    "nickname": "john.doe"
    "email": "john.doe@doe.com"
    "name": "John Doe"
  }
}
```

or even YAML:

``` yaml
simple_user(br.com.easyfactory.model.User):
  id: 1234
  nickname: "john.doe"
  email: "john.doe@doe.com"
  name: "John Doe"
```
